version: "3.1"
services:
  db:
    image: mysql:8.0
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: 127.0.0.1 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: perdepeso
    volumes:
      - ./mysql/:/var/lib/mysql
    networks:
      - default  
  backend:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./backend/:/home/node/app
    ports:
      - "3000:3000"
    links:
      - db
    restart: always
    depends_on:
      - db
    networks:
      - default  
    command: bash -c "npm install && npm start"
